run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - staticcheck
    - govet
    - typecheck
    - ineffassign

    - unused
    - gosimple

    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: ReviewerAssignmentService

issues:
  exclude-dirs:
    - vendor