// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domains "ReviewerAssignmentService/internal/domains"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PRRepository is an autogenerated mock type for the PRRepository type
type PRRepository struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx
func (_m *PRRepository) Count(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, pr
func (_m *PRRepository) Create(ctx context.Context, pr *domains.PullRequest) error {
	ret := _m.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domains.PullRequest) error); ok {
		r0 = rf(ctx, pr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, prName
func (_m *PRRepository) Exists(ctx context.Context, prName string) (bool, error) {
	ret := _m.Called(ctx, prName)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, prName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, prName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PRRepository) GetByID(ctx context.Context, id string) (*domains.PullRequest, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domains.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domains.PullRequest, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domains.PullRequest); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domains.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByReviewer provides a mock function with given fields: ctx, reviewerID
func (_m *PRRepository) GetByReviewer(ctx context.Context, reviewerID string) ([]*domains.PullRequestShort, error) {
	ret := _m.Called(ctx, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetByReviewer")
	}

	var r0 []*domains.PullRequestShort
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domains.PullRequestShort, error)); ok {
		return rf(ctx, reviewerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domains.PullRequestShort); ok {
		r0 = rf(ctx, reviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domains.PullRequestShort)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, reviewerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, pr
func (_m *PRRepository) Update(ctx context.Context, pr *domains.PullRequest) error {
	ret := _m.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domains.PullRequest) error); ok {
		r0 = rf(ctx, pr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPRRepository creates a new instance of PRRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPRRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PRRepository {
	mock := &PRRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
