// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domains "ReviewerAssignmentService/internal/domains"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PRService is an autogenerated mock type for the PRService type
type PRService struct {
	mock.Mock
}

// CreatePR provides a mock function with given fields: ctx, input
func (_m *PRService) CreatePR(ctx context.Context, input domains.PullRequestInput) (*domains.PullRequest, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreatePR")
	}

	var r0 *domains.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domains.PullRequestInput) (*domains.PullRequest, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domains.PullRequestInput) *domains.PullRequest); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domains.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domains.PullRequestInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MergePR provides a mock function with given fields: ctx, prID
func (_m *PRService) MergePR(ctx context.Context, prID string) (*domains.PullRequest, error) {
	ret := _m.Called(ctx, prID)

	if len(ret) == 0 {
		panic("no return value specified for MergePR")
	}

	var r0 *domains.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domains.PullRequest, error)); ok {
		return rf(ctx, prID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domains.PullRequest); ok {
		r0 = rf(ctx, prID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domains.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateReviewer provides a mock function with given fields: ctx, prID, oldReviewerID
func (_m *PRService) UpdateReviewer(ctx context.Context, prID string, oldReviewerID string) (*domains.PullRequest, string, error) {
	ret := _m.Called(ctx, prID, oldReviewerID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReviewer")
	}

	var r0 *domains.PullRequest
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domains.PullRequest, string, error)); ok {
		return rf(ctx, prID, oldReviewerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domains.PullRequest); ok {
		r0 = rf(ctx, prID, oldReviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domains.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, prID, oldReviewerID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, prID, oldReviewerID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewPRService creates a new instance of PRService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPRService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PRService {
	mock := &PRService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
