// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domains "ReviewerAssignmentService/internal/domains"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TeamService is an autogenerated mock type for the TeamService type
type TeamService struct {
	mock.Mock
}

// CreateTeam provides a mock function with given fields: ctx, team
func (_m *TeamService) CreateTeam(ctx context.Context, team *domains.Team) (*domains.Team, error) {
	ret := _m.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for CreateTeam")
	}

	var r0 *domains.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domains.Team) (*domains.Team, error)); ok {
		return rf(ctx, team)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domains.Team) *domains.Team); ok {
		r0 = rf(ctx, team)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domains.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domains.Team) error); ok {
		r1 = rf(ctx, team)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTeam provides a mock function with given fields: ctx, name
func (_m *TeamService) GetTeam(ctx context.Context, name string) (*domains.Team, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *domains.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domains.Team, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domains.Team); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domains.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTeamService creates a new instance of TeamService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamService {
	mock := &TeamService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
